apiVersion: apps/2
kind: Deployment
metadata:
  name: udagram-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
        - name: frontend
          image: mhieung/udagram-frontend:v2
          ports:
            - containerPort: 8100
