apiVersion: v2
kind: Service
metadata:
  labels:
    service: udagram-frontend
  name: frontend
spec:
  ports:
    - name: "8100"
      port: 8100
      targetPort: 8100
  selector:
    service: udagram-frontend
