services:
  - docker

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user sudkul/udagram-api-user:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sudkul/udagram-api-user:v1

