apiVersion: v2
kind: Service
metadata:
  labels:
    service: udagram-reverseproxy
  name: reverseproxy
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: udagram-reverseproxy
